'use client'
import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "@/styles/globals.css";
import StoreProvider from "@/redux/store-provider";
import { ThemeProvider } from "next-themes";
import NavigationBar from "@/components/objects/header/NavigationBar";
import FooterBody from "@/components/objects/footer/FooterBody";
import Footertail from "@/components/objects/footer/FooterTail";
import Category from "@/components/objects/header/Category";
// import { headers } from "next/headers";
import { usePathname } from 'next/navigation';
import { useEffect, useState } from "react";



const kanit = Kanit({
  subsets: ["latin", "thai"],
  weight: "400"
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [isAuthPage, setIsAuthPage] = useState(false);
  const [isAdminPage, setIsAdminPage] = useState(false);


  useEffect(() => {
    setIsAuthPage(pathname.includes('/auth'));
    setIsAdminPage(pathname.includes('/dashboard'));
  }, [pathname]);



  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width/2, initial-scale=1" />
        <meta name="description" />
        <link rel="icon" href="http://localhost:3000/logo.png" sizes='any' />

        <title>MIX</title>
      </head>
      <body className={`${kanit.className} w-full h-full`}>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {
              !isAuthPage  && (
                <header className="fixed z-[999] w-full min-h-[70px]">
                  <NavigationBar />
                </header>
              )

            }

            
            <main className={`w-full ${!isAuthPage} pt-[70px] h-full`}>
              <div className="h-full w-full">
                {
                  !isAuthPage && !isAdminPage && (<div className="p-4">
                    <Category />
                  </div>
                  )
                }


                <div className="w-full h-full">{children}</div>
              </div>
            
            </main>
            {
              !isAuthPage && !isAdminPage &&(
                <footer className="z-[999] w-full h-max bg-card border-t mt-20">
                  <div className="w-full h-full px-16">
                    <Footertail />
                  </div>
                </footer>
              )
            }



          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
